import type { Metadata, Viewport } from "next";
import { fontVariables } from "@/lib/fonts";
import { themeScript } from "@/lib/theme";
import { PAPER, PAPER_DARK } from "@/lib/tokens";
import "./globals.css";

/**
 * The root layout. It does three jobs and deliberately no more: publish the four font variables,
 * set the document metadata, and stamp the theme before the first paint.
 *
 * That last job is new, and it is the mechanism behind D1 — one theme for the whole app. Both rooms
 * read one token sheet and one `data-theme`, so the attribute belongs here, on <html>, rather than
 * on the Desk shell where it used to live.
 *
 * It is stamped by an inline script, NOT by a server-side cookie read, and the reason is worth
 * stating because it is not obvious: calling `cookies()` in the root layout opts EVERY route into
 * dynamic rendering. That would include /login and /offline, which are `force-static` precisely so
 * the service worker can precache them — the offline experience would quietly stop working, and no
 * test would necessarily catch it. The inline script reads `document.cookie` before paint instead:
 * no flash, no dynamic routes, no cost.
 */

/**
 * Where the app lives, for the metadata fields that require an ABSOLUTE url.
 *
 * Unfurlers (Slack, iMessage, Twitter) will not follow a relative OG image — they refuse it — so
 * `metadataBase` has to resolve to a real origin at build time. APP_BASE_URL is the same variable
 * the pipeline already uses to revalidate the Desk, so there is one answer to "where is this app"
 * and not two. The Vercel fallback keeps preview deployments honest, and localhost keeps a
 * developer's build from throwing.
 */
const baseUrl =
  process.env.APP_BASE_URL ??
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "http://localhost:3000");

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: "myStockMarket",
  description: "US-market command center & learning hub",
  // The app sits behind a login wall for data-licensing reasons (plan §1.5, rule 15).
  // Telling crawlers not to index it is belt-and-braces on top of that wall.
  robots: { index: false, follow: false },

  /**
   * The tab icon and the iOS home screen (PD2, plan 5.4). Every one of these paths is already
   * allowed through the login wall by proxy.ts — the browser and the OS fetch them before any
   * session exists, and an icon that 302'd to /login would break the install prompt.
   *
   * Note what this REPAIRS: proxy.ts has allowlisted `/favicon.ico` since P0, and no such file has
   * ever existed. The old generator wrote `favicon.png`, nothing linked it, and the app has been
   * shipping with a blank tab this whole time. It has one now.
   */
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "16x16 32x32 48x48", type: "image/x-icon" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },

  /**
   * THE LINK PREVIEW — and it is the only public face this product has.
   *
   * Every page is behind the login wall, so a link pasted into Slack or iMessage can never show a
   * page. The card is what it shows instead: the mark, the wordmark, one line about what this is.
   * No data, no numbers, no screenshot of the UI — a screenshot would go stale the day the
   * interface moved, and it would be advertising a page the reader cannot open (plan 0.2.5).
   *
   * It is generated by scripts/brand-assets.mjs and echoes the login panel's composition on
   * purpose, so the preview and the page it opens read as one product.
   */
  openGraph: {
    type: "website",
    siteName: "myStockMarket",
    title: "myStockMarket",
    description: "US equities, after the close.",
    url: baseUrl,
    images: [{ url: "/icons/og-card.png", width: 1200, height: 630, alt: "myStockMarket" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "myStockMarket",
    description: "US equities, after the close.",
    images: ["/icons/og-card.png"],
  },
};

/**
 * `viewportFit: "cover"` lets the sticky top bar and the bottom tab bar paint into an iPhone's
 * safe areas; those components then pad themselves back out with env(safe-area-inset-*). Without
 * it, an installed standalone PWA renders letterboxed on a notched phone.
 *
 * `themeColor` is the SSR default: a media pair that follows the OS. That is the honest default
 * before any JavaScript runs — and when the reader has made an explicit choice, the pre-paint
 * script replaces the pair with their chosen paper, so a Midnight reader on a light-mode phone does
 * not get a bone-white status bar sitting over a dark app.
 *
 * There is no maximum-scale lock: the Desk is dense, so pinch-zoom is an accessibility right, not
 * an annoyance to design away.
 */
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: PAPER },
    { media: "(prefers-color-scheme: dark)", color: PAPER_DARK },
  ],
  viewportFit: "cover",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontVariables} suppressHydrationWarning>
      <head>
        {/* Runs before the first paint. See lib/theme.ts for why this is a script and not a cookie read. */}
        <script dangerouslySetInnerHTML={{ __html: themeScript(PAPER, PAPER_DARK) }} />
      </head>
      <body>{children}</body>
    </html>
  );
}
