import { AppWash } from "@/components/AppWash";
import { PageContainer } from "@/components/PageContainer";
import { BrandMark } from "@/components/BrandMark";
import { MacroBoard } from "@/components/desk/MacroBoard";
import { PipelineStrip } from "@/components/desk/PipelineStrip";
import { buildMacroBoard, type MacroStatRow } from "@/lib/macro-board";
import { MacroPulse } from "@/components/desk/MacroPulse";
import { BaseRate } from "@/components/BaseRate";
import { SectionMasthead } from "@/components/SectionMasthead";
import { KitSpecimens } from "./KitSpecimens";
import { StatFigure } from "@/components/StatFigure";
import { RangeBands } from "@/components/ticker/RangeBands";
import { Surface } from "@/components/Surface";
import { NewsImage } from "@/components/news/NewsImage";
import { Tag } from "@/components/Tag";
import { TickerChip } from "@/components/TickerChip";
import { DeltaChip } from "@/components/DeltaChip";
import { OutcomeChip } from "@/components/OutcomeChip";
import { TermProse } from "@/components/Term";
import { VerifiedProse } from "@/components/KeyFigure";
import { copy, fill } from "@/lib/copy";
import type { LadderBand } from "@/lib/range-ladder";

/**
 * /styleguide — the design system as a page you can look at.
 *
 * The anti-drift instrument (§3.10, §5.8): every token and primitive renders here, the VRT suite
 * screenshots each section, and the phase-exit checklist runs against it with actual eyes. If a token
 * silently changes value or a primitive grows a shadow, this is where it becomes visible. It lives behind
 * the login wall and is excluded from navigation — a dev/CI surface, not a product one. The one fixed
 * timestamp below is intentional: a styleguide whose clock moves reshoots every run.
 */

/** Frozen so the visual-regression baseline is stable. 16:05 ET on 9 July 2026. */
const FROZEN_INSTANT = new Date("2026-07-09T20:05:00Z");

export default function StyleguidePage() {
  return (
    <>
      <AppWash />
      {/*
       * The living spec sits in the app's ONE container (PD3, §6.4), like every room it documents. It once
       * stated the measure by hand with a 20px phone gutter where every room uses 16px; the gutter now
       * comes from PageContainer, the only place the measure is decided.
       */}
      <div className="relative z-10 min-h-dvh pb-24 text-ink">
        <PageContainer className="flex flex-col gap-12 pt-8">
          <header>
            <h1 className="font-display text-display font-bold text-ink">Morning Broadsheet</h1>
            <p className="max-w-[62ch] pt-3 font-prose text-prose text-ink-2">
              The living specification. An editorial serif over mono numerals, one lavender
              morning-light wash across the whole app, glass cards with soft depth, hairlines inside
              cards, one hero figure per view. Colour is scarce and always means something. If a
              screenshot of this app could be mistaken for a template — austere <em>or</em> glossy —
              the design is wrong.
            </p>
          </header>

          <Identity />
          <Colours />
          <Voice />
          <Surfaces />
          <Typography />
          <Chips />
          <Controls />
          <Figures />
          <MotionSpec />
          <CopyDeck />
          <Kit />
          <FreshnessLadder />
          <NewsImageLadder />
          <DegradedMacro />
          <DegradedBoard />
          <SuppressedGauge />
        </PageContainer>
      </div>
    </>
  );
}

/** A section wrapper. Each part of the spec is its own screenshot target for the VRT. */
function Section({
  id,
  index,
  title,
  intro,
  children,
}: {
  id: string;
  index: number;
  title: string;
  intro: string;
  children: React.ReactNode;
}) {
  return (
    <section id={id} data-vrt-section={id} aria-label={title}>
      <SectionMasthead index={index} title={title} />
      <p className="max-w-[70ch] pt-3 font-ui text-sm text-ink-2">{intro}</p>
      <div className="pt-5">{children}</div>
    </section>
  );
}

/* ────────────────────────────────────────────────────────────────────────────────────────── */

/**
 * THE IDENTITY (PD2, plan 5.7) — the mark, its three lockups, and the one public face. It is a permanent
 * spec AND a TEST: every image is generated by scripts/brand-assets.mjs from one master and photographed
 * in both themes, so the identity cannot change without a baseline moving and a person explaining why —
 * which matters most for the OG card no product page renders (else the generator could quietly change the
 * link preview and the first anyone knows is a stranger's Slack). The mark shows only at the three named
 * lockups in components/BrandMark.tsx; arbitrary sizes would advertise a freedom that does not exist.
 */
function Identity() {
  const lockups = [
    { size: "inline" as const, label: "inline · 20px", where: "the settings about line" },
    { size: "bar" as const, label: "bar · 28px", where: "the top bar, every room" },
    { size: "panel" as const, label: "panel · 96px", where: "the login panel" },
  ];

  return (
    <Section
      id="identity"
      index={15}
      title="Identity"
      intro="One mark, one master, one generator. A circular mark — a white M with a candlestick ascent and an open book, on a deep indigo field inside a violet ring. It appears in exactly three places in the product, and it never appears on the Desk masthead: the masthead is the DATE, which is the product's hero, and the mark lives in the chrome above it. Restraint is the brand here."
    >
      <div className="flex flex-col gap-8">
        <div className="flex flex-wrap items-end gap-10">
          {lockups.map((lockup) => (
            <figure key={lockup.size} className="flex flex-col items-start gap-3">
              <BrandMark size={lockup.size} />
              <figcaption className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
                {lockup.label}
                <span className="block pt-1 font-ui text-xs normal-case tracking-normal text-ink-2">
                  {lockup.where}
                </span>
              </figcaption>
            </figure>
          ))}
        </div>

        <figure className="flex flex-col items-start gap-3">
          <BrandMark size="card" className="max-w-full rounded-card" />
          <figcaption className="max-w-[70ch] font-ui text-xs text-ink-2">
            The link preview (1200×630, shown at half size). Every page in this app is behind the
            login wall, so a link pasted into Slack can never show a page — this is what it shows
            instead. It carries no data, no numbers and no screenshot of the interface: a screenshot
            would go stale the day the design moved, and it would be advertising a page the reader
            cannot open.
          </figcaption>
        </figure>
      </div>
    </Section>
  );
}

/**
 * Every colour token with the RULE that governs its use — the rules, not the hexes, are what stop a
 * palette from drifting. The reserved-region row matters most, and it is spelled out, not implied.
 */
function Colours() {
  const groups: Array<{
    heading: string;
    note: string;
    swatches: Array<{ name: string; className: string; note: string }>;
  }> = [
    {
      heading: "Neutrals",
      note: "The paper, the ink, and the hairlines. Whitespace is still the main material.",
      swatches: [
        { name: "paper", className: "bg-paper", note: "the page plane, under the wash" },
        { name: "ink", className: "bg-ink", note: "primary text; the hero numeral, always" },
        { name: "ink-2", className: "bg-ink-2", note: "secondary text" },
        { name: "muted", className: "bg-muted", note: "PROVENANCE — clears 4.5:1, by test" },
        { name: "faint", className: "bg-faint", note: "placeholders; never body text" },
        { name: "hairline", className: "bg-hairline", note: "borders and rules inside cards" },
        { name: "hairline-strong", className: "bg-hairline-strong", note: "the masthead rule" },
      ],
    },
    {
      heading: "Accent — interactive only",
      note: "Indigo means “you can act here”. It never appears on data and never on status. Eight indigo mastheads down the Desk would teach the reader that indigo means “chrome”, and the accent would stop meaning anything at all.",
      swatches: [
        { name: "accent", className: "bg-accent", note: "washes, icons, marks" },
        { name: "accent-deep", className: "bg-accent-deep", note: "links and interactive text" },
        { name: "accent-soft", className: "bg-accent-soft", note: "the active-pill wash" },
        { name: "accent-muted", className: "bg-accent-muted", note: "tinted panels" },
      ],
    },
    {
      heading: "Semantic pair — data only",
      note: "Blue/orange, colourblind-safe. Always redundantly encoded: a triangle, a sign, and the word. Colour is never the only channel. The plain variants are for chart strokes and ≥21px figures; the -text variants are darkened to clear AA in small type.",
      swatches: [
        { name: "up", className: "bg-up", note: "gain — strokes, candles, ≥21px" },
        { name: "up-text", className: "bg-up-text", note: "gain, in small type" },
        { name: "down", className: "bg-down", note: "loss — strokes, candles, ≥21px" },
        { name: "down-text", className: "bg-down-text", note: "loss, in small type" },
      ],
    },
    {
      heading: "Band — uncertainty, non-directional",
      note: "Deliberately greyer than the accent, so an uncertainty band never reads as clickable — and deliberately not the up/down pair, so a symmetric historical range carries no directional valence.",
      swatches: [
        { name: "band", className: "bg-band", note: "range-band fills, and nothing else" },
        { name: "band-inner", className: "bg-band-inner", note: "the 50% range" },
        { name: "band-outer", className: "bg-band-outer", note: "the 80% range" },
      ],
    },
    {
      heading: "RESERVED — the amber–orange region",
      note: "The REGION is reserved, not merely the hex. Its only occupants are losses and amber's three consumers: the verification-gate flag, the fired-signal marker, and (added in N2) the pipeline strip when a session's edition never landed. No chip, tier, grade, or module hue may sit anywhere in this band — a Desk full of amber-ish “moderate” chips would drown the gate flag even with no hex collision. A unit test measures the hues; a grep counts the consumers.",
      swatches: [
        { name: "alert", className: "bg-alert", note: "gate flag · fired signal · stale pipeline" },
        { name: "alert-wash", className: "bg-alert-wash", note: "the wash behind them" },
        { name: "down", className: "bg-down", note: "a loss — the region's other rightful tenant" },
      ],
    },
    {
      heading: "DANGER — one consumer, and only one, ever",
      note: "Amber says “something degraded”. Red says something else entirely: “do not trust the numbers on this page.” Exactly one surface may make that claim — the pipeline strip's DEAD state — because the moment a second one can, the reader has to work out which red is which, and a colour that needs interpreting is not an alarm. It borrows the hue the palette already owns (the folklore grade's red, hue 0°, outside the reserved amber band) so no new hue enters the app; what it does not borrow is the meaning. Drift rule 19 fails the build for a second consumer.",
      swatches: [
        { name: "danger", className: "bg-danger", note: "the dead pipeline. Nothing else, ever." },
        { name: "danger-wash", className: "bg-danger-wash", note: "the banner's fill" },
      ],
    },
    {
      heading: "Tiers and grades",
      note: "Moderate and mixed are TEAL, not amber — pushed out of the reserved region above. Green → teal → grey is an ordinal ramp, which is what an evidence scale wants anyway.",
      swatches: [
        { name: "tier-strong", className: "bg-tier-strong", note: "strong" },
        { name: "tier-moderate", className: "bg-tier-moderate", note: "moderate — teal" },
        { name: "tier-weak", className: "bg-tier-weak", note: "weak" },
        { name: "grade-supported", className: "bg-grade-supported", note: "supported" },
        { name: "grade-mixed", className: "bg-grade-mixed", note: "mixed — teal" },
        { name: "grade-weak", className: "bg-grade-weak", note: "weak — rust" },
        { name: "grade-folklore", className: "bg-grade-folklore", note: "folklore — red" },
      ],
    },
  ];

  return (
    <Section
      id="tokens"
      index={1}
      title="Colour"
      intro="Every colour in the product, and the rule that governs it. Both rooms and both themes read this one sheet; there is no room palette and no second column."
    >
      <div className="flex flex-col gap-7">
        {groups.map((group) => (
          <div key={group.heading}>
            <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
              {group.heading}
            </h3>
            <p className="max-w-[70ch] pt-1 font-ui text-2xs text-muted">{group.note}</p>
            <ul className="flex flex-wrap gap-4 pt-3">
              {group.swatches.map((s) => (
                <li key={`${group.heading}-${s.name}`} className="flex items-start gap-2">
                  <span
                    className={`mt-0.5 size-5 shrink-0 rounded-chip border border-hairline ${s.className}`}
                  />
                  <span className="flex flex-col">
                    <span className="font-mono text-2xs text-ink">{s.name}</span>
                    <span className="font-ui text-2xs text-muted">{s.note}</span>
                  </span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </Section>
  );
}

/**
 * VOICE & EMPHASIS (PD5, plan §8) — the richness kit and the complete colour dictionary. The permanent
 * spec the eyeball pass reads against, carrying the §8.5 table: every colour, what it MEANS, and who may
 * use it (the 3.10 pass gains "every coloured element here appears in the dictionary", checkable only
 * because it is here). It is a GRID, not a `<table>`, deliberately: drift rule 16 reserves `<table>` for
 * DataTable, the app's one DATA instrument; this is a SPECIFICATION, never sorted, authored not queried.
 */
function Voice() {
  /**
   * THE COLOUR DICTIONARY (§8.5, ruling E6) — the complete list of things colour may mean. E6's promise is
   * this list did not GROW in Parts 5–11: anything on screen carrying a hue must appear here or it is
   * drift. The `guard` column is the point — a meaning with no enforcement is one that will be borrowed.
   */
  const dictionary = [
    {
      family: "Direction",
      swatches: ["bg-up", "bg-down"],
      means: "A price moved up or down — or a thing turned out well or badly. The ONE data pair.",
      // TWO doors, and drift rule 28 holds them shut: a direction-coloured BACKGROUND is what makes
      // a chip a chip, and any hand-rolled seventh copy has to paint one to exist.
      consumers: "DeltaChip · OutcomeChip — the two doors (rule 28) · sparklines · candles · range strokes",
      guard: "Never the only channel — a glyph, a sign, or the WORD rides with it, always (P7).",
    },
    {
      family: "Accent (indigo)",
      swatches: ["bg-accent", "bg-accent-soft"],
      means: "Interactivity. This is a door, or the thing you are on.",
      consumers: "Links · the active nav pill · focus rings · a TickerChip's hover wash",
      guard: "It means nothing else. A definition is NOT a call to act — Term is ink, not accent.",
    },
    {
      family: "Tier",
      swatches: ["bg-tier-strong", "bg-tier-moderate", "bg-tier-weak"],
      means: "How a historical tendency looks: strong, moderate, weak.",
      consumers: "Tag variant=\"tier\" — and nothing else",
      guard: "The WORD is always inside the chip. A coloured dot is not a claim.",
    },
    {
      family: "Grade",
      swatches: ["bg-grade-supported", "bg-grade-mixed", "bg-grade-weak", "bg-grade-folklore"],
      means: "How well the research record supports a technique.",
      consumers: "Tag variant=\"grade\" / \"folklore\"",
      guard: "Same rule: the grade's name is in the chip, in text.",
    },
    {
      family: "Alert (amber)",
      swatches: ["bg-alert", "bg-alert-wash"],
      means: "Something DEGRADED. Read this with suspicion.",
      consumers: "The verification-gate flag · the fired-signal marker · a stale pipeline strip",
      guard: "The REGION is reserved, not the hex. Drift rule 5 counts the consumers.",
    },
    {
      family: "Danger (red)",
      swatches: ["bg-danger", "bg-danger-wash"],
      means: "Do not trust the numbers on this page.",
      consumers: "PipelineStrip's DEAD state. One consumer, and only one, ever.",
      guard: "Drift rule 19 fails the build on a second one.",
    },
    {
      family: "Band",
      swatches: ["bg-band-inner", "bg-band-outer"],
      means: "Uncertainty. A range, with no direction in it.",
      consumers: "The range ladder's fills, and nothing else",
      guard: "Greyer than accent (so it never reads clickable) and NOT the up/down pair (so a symmetric range carries no valence).",
    },
    {
      family: "Academy modules",
      swatches: [
        "bg-module-foundations",
        "bg-module-structure",
        "bg-module-patterns",
        "bg-module-risk",
      ],
      means: "NOTHING. These are DECORATIVE — they distinguish four shelves of a library.",
      consumers: "Academy module bars",
      guard: "Labelled decorative here on purpose: they are the one place in the app where a hue is allowed to mean nothing, so they must never be read as a scale. None is amber; none is the accent.",
    },
  ];

  return (
    <Section
      id="voice"
      index={16}
      title="Voice & emphasis"
      intro="The richness kit — how a symbol, a term and a verified figure are set — and the complete dictionary of what colour is allowed to mean. Richness is texture, weight and hierarchy AT REST: nothing here moves, and nothing here adds a hue."
    >
      <div className="flex flex-col gap-8">
        {/* ── The kit ─────────────────────────────────────────────────────────────────────── */}
        <div>
          <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            TickerChip — one symbol, one treatment
          </h3>
          <p className="max-w-[70ch] pt-1 font-ui text-2xs text-muted">
            A door where a door is legal (a table cell); a label where an ancestor is already
            interactive (a news card is one big link; a movers row is a button). Same chip either
            way. The trailing move is money — it carries <code>data-p2</code> and never animates.
          </p>
          <ul className="flex flex-wrap items-center gap-3 pt-3">
            <li>
              <TickerChip symbol="AAPL" door />
            </li>
            <li>
              <TickerChip symbol="AAPL" />
            </li>
            <li>
              <TickerChip symbol="SMCI" door move={{ value: "+18.40%", direction: "up", window: "1D" }} />
            </li>
            <li>
              <TickerChip symbol="NVDA" move={{ value: "-2.10%", direction: "down", window: "1D" }} />
            </li>
          </ul>
        </div>

        <div>
          <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            DeltaChip — the app&rsquo;s one delta, and its two atoms
          </h3>
          <p className="max-w-[70ch] pt-1 font-ui text-2xs text-muted">
            The signed delta and its window. It breaks BETWEEN the two atoms and never inside one —
            a phrase broken one word per line has not been wrapped, it has been shattered. Flat gets
            no triangle: inventing a direction would be inventing a fact.
          </p>
          <ul className="flex flex-wrap items-center gap-3 pt-3">
            <li>
              <DeltaChip value="+0.29%" direction="up" window="1D" />
            </li>
            <li>
              <DeltaChip value="-0.55%" direction="down" window="vs prior week" />
            </li>
            <li>
              <DeltaChip value="0.00%" direction="flat" window="1D" />
            </li>
          </ul>
        </div>

        <div>
          <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            OutcomeChip — how it turned out, and the word says so
          </h3>
          <p className="max-w-[70ch] pt-1 font-ui text-2xs text-muted">
            The delta chip&rsquo;s sibling: a delta&rsquo;s second atom is the WINDOW it was measured
            over, an outcome&rsquo;s is the WORD for the verdict. A hit and a miss render at
            identical weight and differ only in hue — that is not a style choice, it is the track
            record&rsquo;s honesty claim, and it is asserted in a test that strips the colours off
            both and compares what is left. Neutral is the honest third state: a forecast the market
            never answered is not a miss.
          </p>
          <ul className="flex flex-wrap items-center gap-3 pt-3">
            <li>
              <OutcomeChip tone="positive" label="hit" />
            </li>
            <li>
              <OutcomeChip tone="negative" label="miss" />
            </li>
            <li>
              <OutcomeChip tone="neutral" label="unresolvable" />
            </li>
            <li>
              <OutcomeChip tone="positive" label="gain" figure="+$412.30" />
            </li>
            <li>
              <OutcomeChip tone="negative" label="loss" figure="−$118.05" />
            </li>
          </ul>
        </div>

        <div>
          <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            Term — a doorway, not a highlight
          </h3>
          <p className="max-w-[70ch] pt-1 font-ui text-2xs text-muted">
            A dotted underline in INK. At most two per paragraph, first occurrence per view. It is
            not accent, because accent means &ldquo;do something&rdquo; and a definition is not a
            call to act — it is a word with more behind it if you want it, and nothing at all if you
            don&rsquo;t.
          </p>
          <p className="max-w-[62ch] pt-3 font-prose text-base text-ink-2">
            <TermProse text="Breadth was narrow into the close, and the VIX barely moved." />
          </p>
        </div>

        <div>
          <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            KeyFigure — emphasis is EARNED (E5)
          </h3>
          <p className="max-w-[70ch] pt-1 font-ui text-2xs text-muted">
            A figure is set in mono if and only if the deterministic gate cleared it. The emphasis is
            itself a claim — it says &ldquo;this was checked against its source&rdquo; — so the
            renderer takes verified figures, never raw strings. Below, only <em>18.4%</em> was on the
            gate&rsquo;s allow-list; &ldquo;4th&rdquo; is a number-shaped word the gate never
            checked, and it stays in prose. No colour, no bold, no size bump: the TYPEFACE is the
            receipt.
          </p>
          <p className="max-w-[62ch] pt-3 font-serif text-base italic text-ink-2">
            <VerifiedProse
              text="SMCI jumped 18.4% after raising guidance for the 4th time."
              allowed={["18.4%"]}
            />
          </p>
        </div>

        {/* ── The dictionary (§8.5) ───────────────────────────────────────────────────────── */}
        <div>
          <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            The colour dictionary — the complete list, forever (E6)
          </h3>
          <p className="max-w-[70ch] pt-1 font-ui text-2xs text-muted">
            Every colour this app may use, and what it means. The eyeball pass at every phase exit
            asks one question of every surface: <em>does every coloured element on this screen appear
            in this table?</em> If a hue is on the screen and not in this list, it is drift — no
            matter how good it looks.
          </p>

          <dl className="flex flex-col gap-px pt-4">
            {dictionary.map((entry) => (
              <div
                key={entry.family}
                className="grid gap-x-4 gap-y-1 border-t border-hairline py-3 sm:grid-cols-[10rem_1fr]"
              >
                <dt className="flex flex-col gap-1.5">
                  <span className="font-ui text-2xs font-semibold uppercase tracking-[0.06em] text-ink">
                    {entry.family}
                  </span>
                  <span className="flex gap-1">
                    {entry.swatches.map((className) => (
                      <span
                        key={className}
                        className={`size-4 shrink-0 rounded-chip border border-hairline ${className}`}
                      />
                    ))}
                  </span>
                </dt>
                <dd className="flex flex-col gap-1">
                  <span className="font-prose text-base text-ink-2">{entry.means}</span>
                  <span className="font-mono text-2xs text-muted">{entry.consumers}</span>
                  <span className="max-w-[70ch] font-ui text-2xs text-muted">{entry.guard}</span>
                </dd>
              </div>
            ))}
          </dl>
        </div>

        {/* ── The negative list (§8.4) ────────────────────────────────────────────────────── */}
        <div className="border-t border-hairline pt-5">
          <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            What must never appear (§8.4)
          </h3>
          <p className="max-w-[70ch] pt-1 font-ui text-2xs text-muted">
            Run at every richness exit. Each of these is a treatment somebody will reasonably propose,
            and each is refused for a reason that is not taste.
          </p>
          <ul className="flex max-w-[70ch] flex-col gap-1.5 pt-3">
            {[
              "No motion on any data at rest — a number that moves is a number that looks like it is happening (P2).",
              "No new hue meanings — walk every coloured element against the dictionary above (E6).",
              "No bold inside Newsreader prose — the weight is not loaded, so the browser fakes it (drift rule 27).",
              "No icon as decoration — functional icons only.",
              "No colour-only signal, anywhere — a glyph or a word rides with every hue (P7).",
              "No emphasis on an unverified number — the mono IS the claim (E5).",
              "No underline that is not a doorway.",
              "Masthead chrome stays muted — the “alive” comes from content, never from chrome.",
              "No score-like heat tints on movers — magnitude already speaks through the figures (P6).",
            ].map((line) => (
              <li key={line} className="flex gap-2 font-ui text-2xs text-ink-2">
                <span aria-hidden="true" className="text-muted">
                  ·
                </span>
                {line}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </Section>
  );
}

/** The surface levels, rendered as themselves. */
function Surfaces() {
  return (
    <Section
      id="surfaces"
      index={2}
      title="Surfaces and elevation"
      intro="Depth is atmospheric, never skeuomorphic. Cards NEVER blur — stacked backdrop-filters are a GPU tax that shows up as scroll jank on a mid-range phone, and over a static wash, translucency alone looks near-identical. Blur is spent only on the sticky bars and the overlays."
    >
      <div className="grid gap-4 md:grid-cols-2 desk:grid-cols-4">
        <Surface level="card" as="div" className="p-5">
          <p className="font-mono text-2xs uppercase tracking-[0.06em] text-muted">L1 · card</p>
          <p className="pt-2 font-ui text-sm text-ink-2">
            Translucent glass, hairline border, 16px radius. Every Desk module.
          </p>
        </Surface>
        <Surface level="raised" as="div" className="p-5">
          <p className="font-mono text-2xs uppercase tracking-[0.06em] text-muted">L2 · raised</p>
          <p className="pt-2 font-ui text-sm text-ink-2">
            More opaque, soft shadow. Stat cards, and cards the layout wants to lift.
          </p>
        </Surface>
        <Surface level="tinted" as="div" className="p-5">
          <p className="font-mono text-2xs uppercase tracking-[0.06em] text-muted">tinted</p>
          <p className="pt-2 font-ui text-sm text-ink-2">
            An accent-washed nested panel. Base-rate panels, the cost mirror, helper boxes.
          </p>
        </Surface>
        <Surface level="solid" as="div" className="p-5">
          <p className="font-mono text-2xs uppercase tracking-[0.06em] text-muted">solid</p>
          <p className="pt-2 font-ui text-sm text-ink-2">
            Opaque paper, no glass. The Academy&rsquo;s material — and every decision moment, where
            the surface stops being atmospheric and becomes a page.
          </p>
        </Surface>
      </div>
    </Section>
  );
}

/** The four families, and the serif floor that explains why there are two serifs. */
function Typography() {
  return (
    <Section
      id="type"
      index={3}
      title="Typography"
      intro="Four families. Playfair Display sets titles and never a number. Inter is every label and control. JetBrains Mono is every numeral in the product, without exception. Newsreader is prose — and the small editorial italics Playfair is too fragile to set."
    >
      <div className="flex flex-col gap-6">
        <div>
          <p className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            display · Playfair Display
          </p>
          <p className="font-display text-display font-bold text-ink">Friday, July 11, 2026</p>
          <p className="font-display text-title font-bold text-ink">
            A card title at the serif floor — 19px
          </p>
        </div>

        <div>
          <p className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            the serif floor — why two serifs exist
          </p>
          <p className="max-w-[62ch] pt-1 font-ui text-2xs text-muted">
            Playfair renders at 19px and above, and never in italic below the display sizes. A
            display serif&rsquo;s hairlines collapse at text sizes. Editorial italics at card sizes
            are Newsreader:
          </p>
          <p className="pt-2 font-prose text-base italic text-ink">
            Golden cross — a text serif holds its hairlines at 15px, where a display serif would not.
          </p>
        </div>

        <div>
          <p className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">ui · Inter</p>
          <p className="font-ui text-base text-ink">
            Every label, control, table cell, and nav item. Never a number.
          </p>
        </div>

        <div>
          <p className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            mono · JetBrains Mono
          </p>
          <p className="font-mono text-num-lg text-ink">6,812.34</p>
          <p className="font-mono text-sm text-ink-2">
            61 of 108 — 56.5% (47–65% CI) · tabular by construction
          </p>
        </div>

        <div>
          <p className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            prose · Newsreader
          </p>
          <p className="max-w-[65ch] font-prose text-prose text-ink">
            The Academy is a reading room, not a tinted dashboard. It shares this palette and this
            theme; what changes is the furniture — solid paper cards, serif kickers, a longer line,
            and more air.
          </p>
        </div>
      </div>
    </Section>
  );
}

/** Chips: colour allowed, the word mandatory. */
function Chips() {
  return (
    <Section
      id="chips"
      index={4}
      title="Chips and tags"
      intro="Colour is allowed on a chip. The WORD inside it is not optional. A coloured dot is not a claim — the word beside it is — so colour is always the redundant channel, and a colourblind reader loses nothing."
    >
      <div className="flex flex-col gap-5">
        <div className="flex flex-wrap items-center gap-3">
          <span className="w-28 font-mono text-2xs uppercase tracking-[0.06em] text-muted">tier</span>
          <Tag variant="tier" tier="strong">
            worth a closer look
          </Tag>
          <Tag variant="tier" tier="moderate">
            note it; check the weakeners
          </Tag>
          <Tag variant="tier" tier="weak">
            watch only
          </Tag>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <span className="w-28 font-mono text-2xs uppercase tracking-[0.06em] text-muted">grade</span>
          <Tag variant="grade" grade="supported">
            supported
          </Tag>
          <Tag variant="grade" grade="mixed">
            mixed
          </Tag>
          <Tag variant="grade" grade="weak">
            weak
          </Tag>
          <Tag variant="folklore" />
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <span className="w-28 font-mono text-2xs uppercase tracking-[0.06em] text-muted">
            catalyst
          </span>
          <Tag variant="catalyst">CPI</Tag>
          <Tag variant="catalyst">FOMC</Tag>
          <Tag variant="catalyst">EARNINGS</Tag>
          <Tag variant="catalyst">ETF proxy</Tag>
        </div>
      </div>
    </Section>
  );
}

/** Buttons and inputs — recipes, not a component library. */
function Controls() {
  return (
    <Section
      id="controls"
      index={5}
      title="Buttons and inputs"
      intro="Recipes rather than components, matching the current architecture. Every control is at least 44px tall on touch, and every input renders at 16px below md — iOS zooms on any focused control under 16px and never zooms back."
    >
      <div className="flex flex-col gap-6">
        <div className="flex flex-wrap items-center gap-3">
          <button
            type="button"
            className="min-h-11 rounded-control bg-[image:var(--gradient-brand)] px-4 py-2 font-ui text-sm font-semibold text-white transition-[filter] duration-(--duration-quick) ease-(--ease-quiet) hover:brightness-105"
          >
            Open my desk →
          </button>
          <button
            type="button"
            className="min-h-11 rounded-control border border-hairline bg-surface px-4 py-2 font-ui text-sm text-ink transition-colors duration-(--duration-quick) hover:border-hairline-strong"
          >
            Secondary
          </button>
          <button
            type="button"
            className="min-h-11 rounded-control border border-hairline px-4 py-2 font-ui text-sm text-down-text transition-colors duration-(--duration-quick) hover:border-hairline-strong"
          >
            Destructive, quietly
          </button>
          <button
            type="button"
            disabled
            className="min-h-11 rounded-control border border-hairline bg-surface px-4 py-2 font-ui text-sm text-ink disabled:opacity-60"
          >
            Disabled
          </button>
        </div>

        <div className="flex flex-wrap items-end gap-4">
          <label className="flex flex-col gap-1">
            <span className="font-mono text-2xs uppercase tracking-[0.06em] text-muted">Symbol</span>
            <input
              defaultValue="AAPL"
              className="min-h-11 rounded-control border border-hairline bg-surface px-3 py-2 font-mono text-input-touch uppercase text-ink md:text-sm"
            />
          </label>
          <label className="flex flex-col gap-1">
            <span className="font-mono text-2xs uppercase tracking-[0.06em] text-muted">Side</span>
            <select className="min-h-11 rounded-control border border-hairline bg-surface px-3 py-2 font-ui text-input-touch text-ink md:text-sm">
              <option>long</option>
              <option>short</option>
            </select>
          </label>
        </div>

        <p className="max-w-[70ch] font-ui text-2xs text-muted">
          One exception, and it is a product rule rather than a style one: in the cooling-off
          interstitial, <em>Sit with it</em> takes the primary style and <em>Proceed</em> the
          secondary. The friction is the point.
        </p>
      </div>
    </Section>
  );
}

/** Figures — including the one hero, and the base rate that may never appear without its context. */
function Figures() {
  return (
    <Section
      id="charts"
      index={6}
      title="Figures and base rates"
      intro="The hero numeral is ink at every scale — never the up/down colour. The largest thing on a screen is never emotional colour: a 64px orange number is a mood; a 64px ink number with a small orange triangle is a fact."
    >
      <div className="flex flex-col gap-8">
        <div className="flex flex-wrap items-end gap-10">
          <StatFigure
            label="S&P 500"
            value="6,812.34"
            scale="hero"
            delta={{ value: "+0.34%", direction: "up", window: "1D" }}
          />
          <StatFigure
            label="Dow"
            value="44,210.55"
            scale="body"
            delta={{ value: "−0.25%", direction: "down", window: "1D" }}
          />
          <StatFigure label="VIX" value="15.84" scale="body" />
        </div>

        <div>
          <p className="pb-2 font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            the one base-rate renderer
          </p>
          <Surface level="tinted" as="div" className="max-w-[62ch] p-5">
            <BaseRate
              data={{
                n: 108,
                wins: 61,
                winRate: 0.565,
                ciLow: 0.47,
                ciHigh: 0.65,
                baseline: 0.54,
                horizonDays: 10,
                refClass: "US large/mid",
                years: 20,
                publicationYear: 2019,
                evidenceGrade: "mixed",
              }}
            />
          </Surface>
          <p className="max-w-[70ch] pt-2 font-ui text-2xs text-muted">
            No other component may render a base rate. The N-gate, the interval, the always-up
            baseline, and the WEAK cap have to travel with the number — so the number lives where
            they live. The proportion bar and the dot array are base-rate displays too, which is
            exactly why they live INSIDE it.
          </p>
        </div>

        {/*
         * The Range Ladder — the app's visual centrepiece, and the drawing most likely to go wrong. It
         * renders on fixture data so it can be reviewed and screenshotted without a seeded database, and so
         * the two honesty locks (no median mark, no connecting cone) can be checked with eyes every phase exit.
         */}
        <div>
          <p className="pb-2 font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            the range ladder — the honest fan, sliced
          </p>
          <Surface level="card" as="div" className="max-w-[68ch] p-5">
            <RangeBands bands={LADDER_SPECIMEN} />
          </Surface>
          <p className="max-w-[70ch] pt-2 font-ui text-2xs text-muted">
            A forward-widening cone is the visual grammar of a projection — the eye reads it as “the
            future goes that way”, whatever the caption says. So the same information is sliced into
            discrete horizons on a signed-return axis. Uncertainty visibly grows with time, and
            nothing points forward. There is no 50th-percentile mark of any kind, and nothing joins
            the rows.
          </p>
        </div>
      </div>
    </Section>
  );
}

/** Fixture bands for the ladder specimen above — realistic shape, obviously synthetic numbers. */
const LADDER_SPECIMEN: LadderBand[] = [
  { horizonDays: 5, coverage: 0.8, lo: -0.043, hi: 0.048, label: "5-day", n: 495, windowDays: 500 },
  { horizonDays: 5, coverage: 0.5, lo: -0.018, hi: 0.021, label: "5-day", n: 495, windowDays: 500 },
  { horizonDays: 10, coverage: 0.8, lo: -0.062, hi: 0.071, label: "10-day", n: 490, windowDays: 500 },
  { horizonDays: 10, coverage: 0.5, lo: -0.027, hi: 0.031, label: "10-day", n: 490, windowDays: 500 },
  { horizonDays: 20, coverage: 0.8, lo: -0.089, hi: 0.104, label: "20-day", n: 480, windowDays: 500 },
  { horizonDays: 20, coverage: 0.5, lo: -0.038, hi: 0.045, label: "20-day", n: 480, windowDays: 500 },
];

/** The motion spec, including the list of things that must never move. */
function MotionSpec() {
  const still = [
    "BaseRate — the sentence, the interval, the baseline",
    "Dot arrays — every dot is one case; misses are hollow",
    "CalibrationScatter",
    "RangeBands — the range ladder",
    "QuantileDotplot",
    "Proportion and breadth bars",
    "Brier figures",
    "StatFigure deltas — money",
  ];

  return (
    <Section
      id="motion-static"
      index={7}
      title="Motion"
      intro="General UI motion is allowed now: hover lifts, drawer slides, a 200ms route fade, the provenance reveal. One easing, no springs, no bounce. Nothing loops, nothing autoplays, and nothing moves to attract attention."
    >
      <div className="grid gap-6 md:grid-cols-2">
        <Surface level="card" as="div" className="p-5">
          <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">Allowed</h3>
          <ul className="flex flex-col gap-1 pt-3 font-ui text-sm text-ink-2">
            <li>Hover and focus colour shifts — 150ms</li>
            <li>Hover lift — only where no probability visual sits inside</li>
            <li>Route transition — 200ms, opacity only, never a translate</li>
            <li>Rail and sheet slides — 240ms</li>
            <li>Charts appear as completed wholes — a fade, never a sweep</li>
            <li>One quiet shimmer on loading placeholders</li>
            <li>The provenance reveal — the signature gesture</li>
          </ul>
        </Surface>

        <Surface level="card" as="div" className="p-5">
          <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">
            Never moves — and neither may its ancestors
          </h3>
          <ul className="flex flex-col gap-1 pt-3 font-ui text-sm text-ink-2">
            {still.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
          <p className="pt-3 font-ui text-2xs text-muted">
            Each of these carries <code className="font-mono">data-p2</code>, and a jsdom test walks
            up from every marked node to prove nothing above it animates or transforms. An animated
            probability implies the probability is <em>arriving</em> — that something is happening
            right now that the reader might be late for. This product exists to say the opposite.
          </p>
          <p className="pt-2 font-ui text-2xs text-muted">
            A candle chart may fade in while a range band may not even do that: a chart is a record,
            and fading in a completed record is showing a photograph. A range band is a claim about
            uncertainty, and any entrance treatment reads as “the forecast is arriving”. Records may
            appear. Claims are simply there.
          </p>
        </Surface>
      </div>
    </Section>
  );
}

/** The copy deck, rendered — because the sentences are the honesty rules in their final form. */
function CopyDeck() {
  const lines: Array<[string, string]> = [
    ["scope.line", copy.scope.line],
    ["baseRate.baseline", fill(copy.baseRate.baseline, { h: "10", pct: "54%" })],
    ["baseRate.insufficient", fill(copy.baseRate.insufficient, { n: "18" })],
    ["volband.caveat", copy.volband.caveat],
    ["mover.noNews", copy.mover.noNews],
    // The macro provenance line is deliberately NOT in this deck: it is composed at render time from the
    // rows that actually appeared (buildMacroProvenance, C6). It used to be a fixed string here — exactly
    // how it came to sit under four ETF prices claiming FRED index levels. The deck holds the FRAGMENTS.
    ["macro.indexesUnavailable", copy.macro.indexesUnavailable],
    ["macro.proxyChipDegraded", fill(copy.macro.proxyChipDegraded, { symbol: "SPY" })],
    ["calendar.empty", copy.calendar.empty],
    ["calendar.emptySub", copy.calendar.emptySub],
    ["brief.unavailable", copy.brief.unavailable],
    ["decision.disclaimer", copy.decision.disclaimer],
  ];

  return (
    <Section
      id="copy"
      index={8}
      title="Copy"
      intro="Every reader-facing sentence that carries a guardrail lives in lib/copy.ts, verbatim. Components never inline a sentence of their own — these strings ARE the honesty rules, in their final human form."
    >
      <Surface level="card" as="div" className="p-5">
        <dl className="flex flex-col gap-3">
          {lines.map(([key, text]) => (
            <div
              key={key}
              className="flex flex-col gap-0.5 border-b border-hairline pb-3 last:border-b-0 last:pb-0"
            >
              <dt className="font-mono text-2xs text-muted">{key}</dt>
              <dd className="max-w-[70ch] font-prose text-base text-ink">{text}</dd>
            </div>
          ))}
        </dl>
      </Surface>

      <p className="pt-4 font-mono text-2xs text-muted">
        Rendered at a frozen instant so the visual-regression baseline is stable:{" "}
        {FROZEN_INSTANT.toISOString()}
      </p>
    </Section>
  );
}

/**
 * 9 — The kit (APP-FEEL Part 3). The primitives that turned the receipt into rooms. Every specimen here
 * is deterministic — this section is the VRT anchor for the whole kit; photographing a skeleton by racing
 * a real page load would be flaky, photographing one here is a pixel lock.
 */
/**
 * 10 — The freshness ladder (NEWS-AND-CONTROL Part 4.1). The three states of the pipeline strip side by
 * side, the ONLY place they can be seen together (in the product they are mutually exclusive, and two
 * appear only on nights nobody wants). Each is driven from a fixed run and clock — pixel locks, not
 * pictures of tonight.
 */
function FreshnessLadder() {
  // Friday 2026-07-10's run is the last completed in all three; only the clock changes — the same data is
  // fresh, stale, or an emergency depending on how many sessions have passed without an edition.
  const friday = { runDate: "2026-07-10", finishedAt: "2026-07-10T22:41:00Z" };
  const specimens = [
    { label: "fresh — read Saturday morning", at: "2026-07-11T09:00:00-04:00", run: friday },
    { label: "aging — read Monday night, Monday's run never landed", at: "2026-07-13T22:00:00-04:00", run: friday },
    { label: "dead — read Tuesday night, two sessions gone", at: "2026-07-14T22:00:00-04:00", run: friday },
    { label: "never — an empty database is not a dead pipeline", at: "2026-07-13T22:00:00-04:00", run: null },
  ];

  return (
    <Section
      id="freshness"
      index={10}
      title="Freshness"
      intro="Module 00 spent the best card on the Desk saying 'last cloud run — Jul 11' in the same quiet voice every day, whether the pipeline was healthy or three days dead. That is not a freshness indicator; it is a decoration that mentions freshness. The rule that replaced it: freshness is prominent in proportion to how BAD the news is. A live pipeline earns one quiet line. A stale one earns amber — which is exactly what the reserved amber is reserved for. A dead one earns the loudest surface in the application, undismissable, because a silently dead pipeline serving stale data is the catastrophic failure mode: the app keeps looking authoritative and keeps being wrong. The escalation is carried three times over — by the colour, by the word, and by the ARIA role — because if it lived only in the hue, a screen-reader user would get the app's calmest voice on its worst night."
    >
      <div className="flex flex-col gap-6">
        {specimens.map((s) => (
          <Surface key={s.label} level="card" as="div" className="p-5">
            <h3 className="font-mono text-2xs uppercase tracking-[0.08em] text-muted">{s.label}</h3>
            <PipelineStrip
              run={s.run}
              serverNow={new Date(s.at).toISOString()}
              sourceCount={14}
              degradedCount={2}
            />
          </Surface>
        ))}
      </div>

      <p className="max-w-[70ch] pt-4 font-ui text-2xs text-muted">
        The clock these are graded against is the READER’S, not the cache’s. The Desk is served from
        a cache, and a cached render carries the clock it was made with — so a strip graded on the
        server would have been graded on the morning the cache was filled. A pipeline that died
        overnight would still have been photographed as “fresh” on the reader’s first paint, by the
        one surface whose entire job is to catch exactly that. The last completed run is data and it
        is cached; “now” is not data, and it is supplied by the browser.
      </p>
    </Section>
  );
}

function Kit() {
  return (
    <Section
      id="kit"
      index={9}
      title="Tables & disclosure"
      intro="The six primitives the app-feel plan added, and the rulings they carry. A table states the order it is in and never calls it 'top'. A disclosure says how much it is hiding and as of when. A shelf moves only when the reader pushes it. A skeleton may stand for a container, never for a number: figure slots load as a still em-dash, and the chart reservation is still geometry — because a pulsing rectangle where a price is about to appear manufactures exactly the anticipation the stillness rule exists to forbid."
    >
      <KitSpecimens />
    </Section>
  );
}

/**
 * 11 — The Macro Pulse, DEGRADED (NEWS-AND-CONTROL Part 3, C6). The state the user screenshotted in
 * production, reproduced deterministically for a pixel lock, because this is the frame the plan opened
 * with. That night FRED's index series returned nothing, every slot fell back to an ETF price, and the
 * footer — a FIXED STRING for the happy path — went on declaring "Index levels · FRED · prior close" under
 * four ETF prices, the hero reading ~755 while the S&P sat near 6,800. A provenance line that can disagree
 * with its surface converts a visible degradation into an invisible lie, so the footer is now COMPOSED
 * from the rows rendered (C6). It lives in the styleguide, not an e2e: driving this through the seeded
 * database means one spec mutating market_context and every later spec (the pixel oracle included) reading
 * what it left — the exact bug that made the Academy baselines unphotographable in N1.
 */
function DegradedMacro() {
  const proxy = (label: string, value: string, symbol: string, delta: string, dir: "up" | "down") => ({
    label,
    value,
    deltaPct: delta,
    direction: dir as never,
    source: "etf-proxy" as const,
    proxySymbol: symbol,
    proxyChip: fill(copy.macro.proxyChipDegraded, { symbol }),
  });

  return (
    <Section
      id="macro-degraded"
      index={11}
      title="Macro pulse — degraded"
      intro="The night FRED's index series fail, every slot falls back to an ETF price. That is honest — an ETF is a real number and the chip says exactly what it is. What is NOT honest is a provenance line that goes on claiming these are index levels, and that is what production printed: the Desk's hero read 755 under the label 'S&P 500' while the index sat near 6,800, with a fixed footer underneath insisting the figure came from FRED. The footer is composed from the rows that actually rendered now, so it cannot disagree with its own surface. Each row carries ONE mark, and on a degraded index slot that mark denies the misreading outright — 'SPY · ETF price — not the index level'."
    >
      <Surface className="p-5 desk:p-6">
        <MacroPulse
          asOf={FROZEN_INSTANT}
          spx={proxy("S&P 500", "754.94", "SPY", "+0.41%", "up")}
          indices={[
            proxy("Nasdaq Composite", "612.30", "QQQ", "+0.62%", "up"),
            proxy("Dow", "441.05", "DIA", "−0.18%", "down"),
            {
              label: "Small caps",
              value: "228.71",
              deltaPct: "+0.94%",
              direction: "up" as never,
              source: "etf-proxy" as const,
              proxySymbol: "IWM",
              // The small-caps slot is a proxy BY DESIGN (FRED deleted every free Russell series in 2019),
              // so its chip is the ordinary one, not the degraded denial — it never claimed an index level.
              proxyChip: fill(copy.macro.proxyChip, { symbol: "IWM" }),
            },
          ]}
          breadth={{ advancers: 3210, decliners: 1780, pctAbove50dma: "61%", asOf: "at Thu's close" }}
          vix="15.84"
          tenYear="4.54%"
          provenance={copy.macro.indexesUnavailable}
        />
      </Surface>
    </Section>
  );
}

/**
 * The macro board's degradation ladder (C7) — every rung side by side. A STYLEGUIDE specimen, not an e2e,
 * for the reason N1 learned: driving a degraded board through the seeded database means one spec mutating
 * macro_stat and every later spec (the pixel oracle included) reading what it left. Read the four cells
 * left to right and the ruling is visible at once: a number current for its cadence is quiet, one too old
 * to trust is amber and SAYS so, a source that failed tonight keeps its value and explains the silence, and
 * a never-reported stat shows an em-dash, not a zero.
 */
function DegradedBoard() {
  const runDate = new Date("2026-07-13T00:00:00.000Z");

  const rows: MacroStatRow[] = [
    // Rung 2 — mid-cycle, and perfectly healthy. A Thursday rate on a Monday is not stale.
    {
      seriesKey: "mortgage30us",
      asOfDate: new Date("2026-07-09T00:00:00.000Z"),
      value: 6.49,
      prior: 6.43,
      asOfLabel: "wk of Jul 9",
      sourceKey: "fred",
      meta: null,
    },
    // Rung 3 — the source could not be reached tonight. The number stands; the silence is explained.
    {
      seriesKey: "usd_npr",
      asOfDate: new Date("2026-07-12T00:00:00.000Z"),
      value: 152.23,
      prior: null,
      asOfLabel: "Jul 12",
      sourceKey: "nrb",
      meta: { buy: 152.23, sell: 152.83 },
    },
    // Rung 5 — a week old on a daily cadence. This is the ONE cell allowed to be loud.
    {
      seriesKey: "gold_usd",
      asOfDate: new Date("2026-07-02T00:00:00.000Z"),
      value: 4085.2,
      prior: 4071.9,
      asOfLabel: "Jul 2",
      sourceKey: "goldapi",
      meta: null,
    },
    // Rung 4 is the ABSENCE of a cpi_yoy row — nothing stored, so the cell says "not yet reported".
  ];

  return (
    <Section
      id="macro-board"
      index={12}
      title="Macro board — the degradation ladder (C7)"
      intro="Five household stats, five ways to fail. A cell that is current for its OWN cadence renders quietly and lets its window label do the work — a Thursday mortgage rate read on a Monday is not stale, it is the newest rate that exists, and a board that went amber over it would be crying wolf four days in five. A cell whose number has aged past three full cadences has stopped being information and started being furniture, so it goes amber and says the word “stale” out loud — never the colour alone, because a screen-reader user would otherwise get this app's calmest voice on one of its worse nights. A source that simply could not be reached tonight keeps its value and explains the silence. And a stat that has never reported at all shows an em-dash and says so: that is gold's honest state in production today, because its API key has not been provisioned, and the board would rather say that than print a number nobody checked."
    >
      <Surface className="p-5">
        <MacroBoard board={buildMacroBoard(rows, { "macro-usd_npr": "degraded" }, runDate)} />
      </Surface>
    </Section>
  );
}

/**
 * The Mood gauge, suppressed — the state ruling C8 exists for. Under three of its five inputs there is no
 * score: not a greyed number, not an average of whatever answered, but no score and the names of the
 * missing instruments. A "mood" from two inputs is those two inputs in a costume, and it would look
 * exactly as authoritative as the real thing.
 */
function SuppressedGauge() {
  const runDate = new Date("2026-07-13T00:00:00.000Z");
  const thin: MacroStatRow[] = [
    {
      seriesKey: "mood",
      asOfDate: runDate,
      value: 50,
      prior: null,
      asOfLabel: "Jul 13",
      sourceKey: "computed",
      meta: {
        score: 50,
        band: "mixed",
        components: [
          { key: "breadth", label: "Breadth", value: 0.61, window: "% above the 50-day average", percentile: 0.55 },
          { key: "range", label: "Range position", value: 0.18, window: "near highs minus near lows", percentile: 0.35 },
        ],
      },
    },
  ];

  return (
    <Section
      id="mood-suppressed"
      index={13}
      title="Mood gauge — suppressed"
      intro="The gauge needs three of its five inputs. With two, it does not render a number at all — it names what is missing. This is the same instinct the base rates run on: below the sample size at which a figure means something, the figure is suppressed rather than shrunk or hedged. And it is the whole argument for building this gauge instead of borrowing CNN's: a number you cannot take apart is a number you have to trust, so when it cannot show its work, it does not show."
    >
      <Surface className="p-5">
        <MacroBoard board={buildMacroBoard(thin, null, runDate)} />
      </Surface>
    </Section>
  );
}

/**
 * The four image rungs side by side (plan 7.9). It exists so the fallbacks can be JUDGED, not assumed:
 * the claim ("a text-treatment card beside a photo card reads as an editorial choice, not a failure") is
 * only knowable by putting them together and looking. The oracle locks them; a human decides. Today L4 is
 * what the whole Front Page renders (the media bucket does not exist yet, P-1), so this is the room, not a
 * corner case; L3 has no producer until the bucket lands (hotlinking a favicon at render is what 7.9
 * forbids), so it is a latch exercised only here, not dead code.
 */
function NewsImageLadder() {
  const photo = {
    urlCard: "/fixtures/news/fed-decision.jpg",
    urlThumb: "/fixtures/news/fed-decision.jpg",
    urlFull: "/fixtures/news/fed-decision.jpg",
    width: 1200,
    height: 628,
    blurDataUrl: null,
    attributionSource: "Reuters",
    attributionUrl: "https://reuters.com/fed-holds-july",
  };

  return (
    <Section
      id="news-imagery"
      index={14}
      title="News imagery — the four rungs"
      intro="L1 and L2 are the publisher's own photo. L3 and L4 are generated from tokens, and they are first-class outcomes: same geometry, same frame, same visual weight. Every card on the Front Page is L4 today, because the media bucket does not exist yet (P-1)."
    >
      <div className="grid grid-cols-1 gap-4 desk:grid-cols-2">
        <figure className="flex flex-col gap-2">
          <NewsImage image={photo} eventType="macro" tickers={[]} slot="lead" />
          <figcaption className="font-mono text-2xs uppercase tracking-[0.04em] text-muted">
            L1 · the publisher&apos;s photo
          </figcaption>
        </figure>

        <figure className="flex flex-col gap-2">
          <NewsImage
            image={null}
            eventType="ma"
            tickers={["AMD", "NVDA"]}
            favicon={{ url: "/fixtures/news/chip-merger.jpg", source: "Bloomberg" }}
            slot="lead"
          />
          <figcaption className="font-mono text-2xs uppercase tracking-[0.04em] text-muted">
            L3 · publisher identity (dormant until P-1)
          </figcaption>
        </figure>

        <figure className="flex flex-col gap-2">
          <NewsImage image={null} eventType="fda" tickers={["MRNA", "LLY", "PFE"]} slot="lead" />
          <figcaption className="font-mono text-2xs uppercase tracking-[0.04em] text-muted">
            L4 · catalyst identity, with tickers
          </figcaption>
        </figure>

        <figure className="flex flex-col gap-2">
          <NewsImage image={null} eventType="macro" tickers={[]} slot="lead" />
          <figcaption className="font-mono text-2xs uppercase tracking-[0.04em] text-muted">
            L4 · catalyst identity, no listing (C9)
          </figcaption>
        </figure>
      </div>

      <div className="flex items-start gap-3 pt-2">
        <NewsImage image={null} eventType="earnings" tickers={["SMCI"]} slot="thumb" />
        <NewsImage image={photo} eventType="macro" tickers={[]} slot="thumb" />
        <p className="font-ui text-2xs text-muted">
          The row tier&apos;s thumbnails, generated and photographic. The frames match, which is the
          whole claim.
        </p>
      </div>
    </Section>
  );
}
