/**
 * BrandMark — the house mark, and the ONLY component allowed to render it.
 *
 * THIS IS THE SECOND DOOR IN DRIFT RULE 20, AND IT IS ARGUED RATHER THAN ASSUMED.
 * Rule 20 says news imagery renders through components/news/NewsImage.tsx and nowhere else, because
 * a second consumer would hotlink a publisher's photo, ship without width/height, and invent its own
 * empty state. None of those risks exist here: the mark is OUR file, committed to this repo,
 * generated by scripts/brand-assets.mjs, at a fixed intrinsic size, with no fallback rungs and no
 * bucket. It is a different problem that happens to use the same HTML element, so it gets its own
 * door — one door, not a hole in the wall. The rule's allowlist names this file, and the amendment
 * is logged in DECISIONS.md.
 *
 * A plain <img>, deliberately, and not next/image:
 *   - the optimizer has nothing to do — the asset is already the exact size it is displayed at,
 *     twice over for a 2x screen;
 *   - /login is `force-static`, and a plain <img> is static-safe;
 *   - width and height are always explicit, so the mark reserves its box before it loads and the
 *     layout never shifts under the reader (CLS 0 by construction, not by luck).
 *
 * WebP with no PNG fallback is a decision, not an oversight (DECISIONS.md): every browser that can
 * render this app at all — it is built on Tailwind v4 and dvh units — has supported WebP since 2020.
 */

/**
 * Every place the brand's own imagery is allowed to appear, named rather than numbered so a call
 * site says WHERE it is, not how big it is. Each maps to the generated file that serves it: the
 * 28px top bar and the 20px settings line share the 64px asset (2x and 3x respectively), and the
 * login panel's 96px mark uses the 192px asset (2x).
 *
 * `card` is the odd one, and it earns its place. It is the OG card — the link preview — which no
 * page in the product renders, because its whole job is to be fetched by Slack. That means nothing
 * would ever notice if the generator started producing a different one. Putting it in the
 * styleguide puts it in front of the PIXEL ORACLE: the visual-regression baseline photographs it,
 * and the card can no longer change without someone signing for the change.
 */
const LOCKUPS = {
  /** The top bar, beside the wordmark. */
  bar: { w: 28, h: 28, src: "/icons/brandmark-64.webp" },
  /** The settings "about" line — the one place the mark appears inside a room, quietly. */
  inline: { w: 20, h: 20, src: "/icons/brandmark-64.webp" },
  /** The login panel, above the headline. */
  panel: { w: 96, h: 96, src: "/icons/brandmark-192.webp" },
  /**
   * The login on a PHONE, above the headline — the same job as `panel`, at the size a 390px screen
   * can afford (PD4).
   *
   * IT EXISTS BECAUSE THE PHONE HAD NO MARK AT ALL. The brand panel is `hidden lg:flex`, which is the
   * right call for the panel — a phone has room for a headline and a form and little else — but the
   * mark went out with it. So the first page anyone ever opens, on the device most people open it on,
   * showed the product's name in text and nothing of its face. The one surface where a brand is
   * genuinely load-bearing is the one where the reader has not seen the product yet.
   *
   * It reuses the 192px asset rather than the 64px one, and that costs NOTHING: a `display:none`
   * subtree still loads its images, so the phone already downloads brandmark-192.webp for the panel
   * it cannot see. A second file would be a second request to show a smaller picture.
   */
  panelPhone: { w: 48, h: 48, src: "/icons/brandmark-192.webp" },
  /** The link-preview card, at half size, in the styleguide — the living spec, and the oracle. */
  card: { w: 600, h: 315, src: "/icons/og-card.png" },
} as const;

export type BrandMarkSize = keyof typeof LOCKUPS;

export function BrandMark({
  size = "bar",
  /**
   * Empty by default, and that is the correct accessible answer almost everywhere it is used: in
   * the top bar, on the login panel and in settings, the product's name is written in text right
   * beside the mark. Announcing "myStockMarket" twice is noise, not access. Pass the label only
   * where the mark stands alone.
   */
  alt = "",
  className,
}: {
  size?: BrandMarkSize;
  alt?: string;
  className?: string;
}) {
  const { w, h, src } = LOCKUPS[size];
  return (
    // eslint-disable-next-line @next/next/no-img-element -- see the file header: the argued second door.
    <img
      src={src}
      alt={alt}
      width={w}
      height={h}
      draggable={false}
      className={className}
      // The mark is in the top bar of every room and on the login panel — it is never below the
      // fold, so lazy-loading it would only delay the one image the reader sees first.
      loading="eager"
      decoding="sync"
    />
  );
}
